import React from "react";
import App, { Container } from "next/app";
import Image from "next/image";

import Menu from "../components/Menu";
import "../styles/github-gist.css";
import "../styles/globals.css";
import Head from "next/head";

export default class MyApp extends App {
  static async getInitialProps({ Component, router, ctx }) {
    let pageProps = {};

    if (Component.getInitialProps) {
      pageProps = await Component.getInitialProps(ctx);
    }

    return { pageProps };
  }

  render() {
    const { Component, pageProps } = this.props;

    return (
      <>
        <Head>
        <title>Create Next App</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        </Head>
        <div className="leading-normal">
          <div className="sticky top-0 z-10 h-16 py-2 px-4 flex items-center bg-sky-400 text-pink-500">
          <a href="/"><Image src="/favicon.ico" width="50" height="50" className="rounded-lg"></Image></a>
          </div>
          <div className="flex">
            <Menu className="sticky w-48 flex-no-grow flex-shrink border-r" />

            <div
              className="py-8 px-10"
              style={{ maxWidth: "75%", flexBasis: "66.6667%" }}
            >
              <Component {...pageProps} />
            </div>

            <div
              className="sticky w-48 flex-no-grow flex-shrink border-l p-4 right-0 hidden xl:block"
              style={{ flexBasis: 320 }}
            >
              {" "}
            </div>
          </div>
        </div>
      </>
    );
  }
}
